### ISSUE TITLE
The readme doesn't look good in GitHub dark mode

### ISSUE THREAD

**Issue by dllu** [LingDong-/rrpl#14]
As you may know, GitHub recently released dark mode a few weeks ago.

However the readme has many SVG files that do not have a consistently colored background, so they are illegible in dark mode.

![pic](https://s.dllu.net/MvO7kyS3SnuccZ5E.png)

**Comment by LingDong-** [comment]
Hi @dllu,
I just fixed: d165464f8fcf534a7d9f427899311855f7c0e627
Thanks a lot for pointing out!

**Comment by dllu** [comment]
Awesome! That was fast!
