### ISSUE TITLE
How it handles curves

### ISSUE THREAD

**Issue by lancejpollard** [LingDong-/rrpl#3]
I have looked around some (with my limited knowledge of Chinese) to see if Chinese characters _are composed entirely out of straight lines_, or if there are curves sometimes, but didn't get answered. So thought I'd ask how this system handles curves. It seems there are at least slight curves in some strokes, as in [here](https://www.writtenchinese.com/12-advanced-chinese-strokes-to-help-you-write-characters/). By slight curve I mean like a sword might be slightly curved, not like a spiral or anything. Now that I think of it I'm not sure if I've seen a Chinese character with a circle in it. [Here](https://www.pinterest.com/pin/276197389622416080/) it looks like all straight lines. And while [this](https://www.pinterest.com/pin/470837336015256302/) is tempting to think is Chinese characters from far away, it has lots of circles and curves and is actual scene drawings that sort of look like the same style as Chinese characters. So it seems like Chinese characters are mostly straight lines, but wanted to ask just to clarify to make sure. It seems like it would just flatten them out or ignore them.

**Comment by LingDong-** [comment]
Hi there! Thanks for your interest in the project.

The amount of curves in Chinese characters really depends on the font. In Chinese fonts commonly printed and written today, most of the strokes are straight, while some of them are slightly curved. I think your first link pretty much includes all the curved ones. However by all means, one can also have a super straight font (like your second link) or a super curvy font (like your third link), as long as the readers can correctly identify the characters. Historically many different calligraphic styles that varies in curviness exist.

It's just like English fonts: in Helvetica or Times New Roman you get a lot of circles and curves, however in [scifi/techno/LCD fonts](https://www.dafont.com/theme.php?cat=301) you can also have just straight lines.

I'd say the font in your third link is very stylized. The only Chinese character that contains a full circle in most standardized font is "〇", (pronounced líng, meaning zero). The circles you see in that font are actually "口" (pronounced kǒu, meaning mouth), ususally rendered as a rectangle.

My system handles curves by either a) approximating them into a straight line, OR b) using a series of shorter line segments to give the illusion, depending on the curviness.

I hope my explanation is helpful!
